#include <cstddef>
#include "webgpu.hpp"
#include <stdio.h>

#define PRINT_INFO(s) fprintf(f, "\t%s: %lu,\n", #s, sizeof(s))

int main() {

    using namespace wgpu;
    FILE *f = fopen("c_metadata.js", "w");

    fprintf(f, "/* This file was autogenerated */\n\n");
    fprintf(f, "var C_STRUCT = {\n");
    PRINT_INFO(RenderTarget);
    PRINT_INFO(VertexAttribute);
    PRINT_INFO(VertexBufferLayout);
    PRINT_INFO(VertexState);
    PRINT_INFO(BlendComponent);
    PRINT_INFO(BlendState);
    PRINT_INFO(ColorTargetState);
    PRINT_INFO(FragmentState);
    PRINT_INFO(BufferBindingLayout);
    PRINT_INFO(BindGroupLayoutEntry);
    PRINT_INFO(PushConstantRange);
    PRINT_INFO(BindGroupLayoutDescriptor);
    PRINT_INFO(PipelineLayoutDescriptor);
    PRINT_INFO(PrimitiveState);
    PRINT_INFO(StencilFaceState);
    PRINT_INFO(DepthBiasState);
    PRINT_INFO(DepthStencilState);
    PRINT_INFO(MultiSampleState);
    PRINT_INFO(RenderPipelineDescriptor);
    PRINT_INFO(Operations);
    PRINT_INFO(RenderPassColorAttachment);
    PRINT_INFO(RenderPassDepthStencilAttachment);
    PRINT_INFO(RenderPassTimestampWrites);
    PRINT_INFO(RenderPassDescriptor);
    PRINT_INFO(BufferDescriptor);
    fprintf(f, "}");

    fclose(f);
}